# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-20 19:51
from __future__ import unicode_literals

from django.db import migrations, models
from django.utils import timezone


def create_news(apps, schema_editor):
    News = apps.get_model("news", "News")

    login_news = News(title='New login system!',
                      content="""To enable future development of Markdown Notes, we implemented new Authentication system for Log In, Sign Up and several other functionalities. If you will encounter some strange behavior please let us know through Feedback page!""")
    login_news.news_date = timezone.now()
    login_news.save()

    image_paste_news = News(title='Image pasting from clipboard!', content="""New feature! Now you can paste an image directly from your clipboard! Currently supported is only pasting an image data, not an image file! This feature can be handy for example with screenshots.

Browser support for this feature is currently limited to Chrome, Firefox and Internet Explorer 11.""")
    image_paste_news.news_date = timezone.now()
    image_paste_news.save()


class Migration(migrations.Migration):
    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_news)
    ]
