# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-20 19:51
from __future__ import unicode_literals

from django.db import migrations, models
from django.utils import timezone


def create_news(apps, schema_editor):
    News = apps.get_model("news", "News")

    login_news = News(
        title='New login system',
        content="""We implemented a new, improved authentication system. These changes pave the way for native Markdown Notes apps."""
    )
    login_news.news_date = timezone.now()
    login_news.save()

    image_paste_news = News(
        title='Paste images in your notes',
        content="""New feature! You can now paste screenshots and images directly into the editor just as you would in Paint or Photoshop.

This feature is available on Chrome, Firefox and Internet Explorer 11."""
    )
    image_paste_news.news_date = timezone.now()
    image_paste_news.save()


class Migration(migrations.Migration):
    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_news)
    ]
